# LLVM toolchain wrapper targets for bazel_clang_tidy

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "clang_resource_dir",
    srcs = ["@llvm_toolchain_llvm//:lib/clang/19/include/stddef.h"],
)
